logo: Home  # add logo name
title: Information Security Blog, OSCP Experience,OSCP as a college student in india.
description: > #test
OSCP IN INDIA,OSCP AS STUDENT,Saket Saurav OSCP Experience,CYBER SECURITY,HACKING,OSCP EXAM
permalink: ':title/'
baseurl: "/bef" # the subpath of your site, e.g. /blog
url: "https://offsecin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: homepage.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: author_kali.jpg # your photo
author-name: Saket Saurav #your name
about-author: A student and cyber security enthusiast.<br />I am an engineering student currently in third year of Computer Science Department.<br />I have special interest in Network Pentesting , Red Teaming and Bug Hunting.<br /> I am a learner with  an ardent desire to learn more about cyber security. <br /> # about author
email: offseconhtb@gmail.com # your email
#Phone: +919602470565 
#Website: https://dwayne.example.com # you website

# Social link
#google_url:    # add url link
twitter_url:  https://twitter.com/SaketSourav14
instagram_url: https://www.instagram.com/saketsourav_111 # add url link
#interest_url: # add url link
#ribbble_url:  # add url link
#acebook_url:  # add url link

# Disqus
#discus_identifier: offsecin # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
#mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
      
      - jekyll-sitemap
      - jekyll-paginate
      -jekyll-seo-tag

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
